import assert from 'node:assert/strict';
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import os from 'node:os';
const cwd = '<HOME>/Desktop/oss/<WORKTREE>';
const head = '7d0098415ba17bf1f21af2cf6ff5977bb8415f86';
const git = (...args) => execFileSync('git', args, {cwd, encoding:'utf8', env:{...process.env, GIT_NO_LAZY_FETCH:'1', GIT_ALLOW_PROTOCOL:'file'}});
assert.equal(git('rev-parse', 'HEAD').trim(), head);
const file = 'src/gateway/gateway.test.ts';
const original = git('show', `${head}:${file}`);
const edited = fs.readFileSync(`${cwd}/${file}`, 'utf8');
let restored = edited.replace(/        const proofHelperResolvedMs = performance\.now\(\);[\s\S]*?        const proofWaitStartedMs = performance\.now\(\);\n/, '');
restored = restored.replace(/        const proofSettledMs = performance\.now\(\);\n        const proofSettledAt = new Date\(\)\.toISOString\(\);\n/, '');
restored = restored.replace(/        const proofSettledSampleMs = performance\.now\(\);[\s\S]*?        \);\n/, '');
assert.notEqual(restored, edited);
assert.equal(restored, original);
assert.deepEqual(git('diff','--name-only').trim().split('\n'), [file]);
assert.equal((edited.match(/const proofHelperResolvedMs/g)||[]).length, 1);
console.log('PASS: exact head; probe additions removed reproduce HEAD byte-for-byte; only target test file changed.');
console.log(JSON.stringify({head, platform:os.platform(),release:os.release(),arch:os.arch(),logicalCores:os.cpus().length,physicalCores:execFileSync('sysctl',['-n','hw.physicalcpu'],{encoding:'utf8'}).trim(),memoryBytes:os.totalmem(),node:process.version,pnpm:execFileSync('pnpm',['--version'],{cwd,encoding:'utf8'}).trim(),macOS:execFileSync('sw_vers',['-productVersion'],{encoding:'utf8'}).trim()},null,2));
